version: '2'
services:
  mongodbhost:
    image: mongo:3.3.5
    ports:
      - "27017:27017"

  web:
    build: .
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongodbhost

  tcell_web:
    build: .
    command: sh -c "npm prune && npm install tcell-agent && npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongodbhost

  tcell_local_web:
    build: .
    command: sh -c "npm prune && npm install /tcellagent_src && npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ../nodeagent-tcell:/tcellagent_src
      - .:/app
    links:
      - mongodbhost

  #web35
