version: '2'
services:
  mongodbhost:
    image: mongo:3.3.5
    ports:
      - "27017:27017"

  web:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/ejs-waitlist
    links:
      - mongodbhost

  tcell_web:
    build: .
    command: sh -c "npm uninstall tcell-agent && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/ejs-waitlist
      - ./package-docker.released.json:/ejs-waitlist/package.json
    links:
      - mongodbhost

  tcell_local_web:
    build: .
    command: sh -c "npm uninstall tcell-agent && npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ../nodeagent-tcell:/tcellagent_src
      - .:/ejs-waitlist
      - ./package-docker.local.json:/ejs-waitlist/package.json
    links:
      - mongodbhost
